In [3]:
import numpy as np
from filterpy.kalman import MerweScaledSigmaPoints

In [4]:
P = np.array(
[[ 3.36989867e+22, 8.16877779e+22, -6.33009859e+22, 6.74674648e+23, 1.63544008e+24, -1.26732505e+24, -9.96538793e+04, -5.99204709e+04, -5.09209176e+04, -4.62208179e+04],
 [ 8.16877779e+22, 1.98014843e+23, -1.53444395e+23, 1.63544007e+24, 3.96438016e+24, -3.07205209e+24, -2.56801390e+05, -2.30440681e+04, 5.22815302e+04, 7.93332605e+03],
 [-6.33009858e+22, -1.53444394e+23, 1.19628822e+23, -1.26732504e+24, -3.07205213e+24, 2.38058631e+24, 1.29606370e+05, 1.86862990e+05, -7.00042174e+04, 4.05881955e+03],
 [ 6.74674646e+23, 1.63544006e+24, -1.26732504e+24, 1.35074054e+25, 3.27425260e+25, -2.53726346e+25, -1.99513235e+06, -1.19964579e+06, -1.01946879e+06, -9.25369543e+05],
 [ 1.63544007e+24, 3.96438016e+24, -3.07205212e+24, 3.27425260e+25, 7.93693526e+25, -6.15043916e+25, -5.14132345e+06, -4.61354204e+05, 1.04671242e+06, 1.58830057e+05],
 [-1.26732505e+24, -3.07205208e+24, 2.38058631e+24, -2.53726347e+25, -6.15043917e+25, 4.76606178e+25, 2.59480005e+06, 3.74112230e+06, -1.40150976e+06, 8.12601816e+04],
 [-9.96538793e+04, -2.56801390e+05, 1.29606368e+05, -1.99513235e+06, -5.14132345e+06, 2.59480005e+06, 1.00107032e+00, -1.62022940e-07, 5.81993552e-08, -8.73251207e-09],
 [-5.99204709e+04, -2.30440667e+04, 1.86862991e+05, -1.19964581e+06, -4.61354218e+05, 3.74112229e+06, -1.62022940e-07, 9.97960884e-01, -1.40156766e-09, -1.84931607e-09],
 [-5.09209176e+04, 5.22815299e+04, -7.00042177e+04, -1.01946879e+06, 1.04671242e+06, -1.40150976e+06, 5.81993552e-08, -1.40156766e-09, 1.00233111e+00, 1.27624511e-09],
 [-4.62208179e+04, 7.93332611e+03, 4.05881955e+03, -9.25369543e+05, 1.58830057e+05, 8.12601821e+04, -8.73251207e-09, -1.84931607e-09, 1.27624511e-09, 9.96811592e-01]]
)
x = np.array([[-1.37681671e+11],
 [-3.33736731e+11],
 [ 2.57429131e+11],
 [-2.75643985e+12],
 [-6.68168964e+12],
 [ 5.17774857e+12],
 [-9.20693309e-01],
 [-3.44705666e-01],
 [ 1.80523069e-01],
 [-3.02013817e-02]])

In [5]:
np.linalg.eigvals(P)

array([ 1.40887969e+26,  7.21793187e+20,  1.05331679e+19,  1.71341029e+19,
       -2.53591123e+15,  7.97926054e+13,  9.96811511e-01,  9.97960391e-01,
        1.00107024e+00,  1.00233089e+00])

In [6]:
alpha = 0.0001
beta = 2.
kappa = 0.
points = MerweScaledSigmaPoints(n=10, alpha=alpha, beta=beta, kappa=kappa)

In [7]:
points.sigma_points(x.reshape(-1,), P)

LinAlgError: 4-th leading minor of the array is not positive definite

In [8]:
P2 = np.array(
    [[1.81018306e+02, 1.95686737e-01, 1.47244741e+04, 1.57117211e+02, -8.27291924e+00, 1.26038960e+03, -2.00303619e+00, 7.81724448e+00, 1.04035477e+01, 2.41556742e+01], 
     [1.95686737e-01, 1.81784610e+02, 2.00242693e+03, 8.70353448e+00, 1.57614058e+02, 1.36764277e+02, -2.42485059e+01, -1.03703468e+01, 7.86716400e+00, -1.98935098e+00], 
     [1.47244741e+04, 2.00242693e+03, 1.30123437e+12, 2.56407679e+04, 5.30502302e+02, 1.03100732e+10, 5.30020372e+03, -1.78317090e+04, 9.54733115e+02, 2.46372149e+04],
     [1.57117211e+02, 8.70353448e+00, 2.56407679e+04, 2.25226902e+02, 3.76665406e-01, 2.26359405e+03, -1.09152430e+01, 8.01241874e+00, 1.77025533e+01, 4.97803249e+01],
     [-8.27291924e+00, 1.57614058e+02, 5.30502302e+02, 3.76665406e-01, 2.25895014e+02, -4.70831803e+01, -4.99901669e+01, -1.76474276e+01, 8.08071917e+00, -1.08671456e+01],
     [1.26038960e+03, 1.36764277e+02, 1.03100732e+10, 2.26359405e+03, -4.70831803e+01, 9.14170923e+07, 5.52886952e+02, -1.61428412e+03, 1.15086354e+02, 2.22683176e+03],
     [-2.00303619e+00, -2.42485059e+01, 5.30020372e+03, -1.09152430e+01, -4.99901669e+01, 5.52886952e+02, 4.97650043e+01, -3.48174154e+00, 1.89539967e+01, -6.57112562e-03], 
     [7.81724448e+00, -1.03703468e+01, -1.78317090e+04, 8.01241874e+00, -1.76474276e+01, -1.61428412e+03, -3.48174154e+00, 3.40896257e+01, -1.15623253e-02, -1.88895586e+01],
     [1.04035477e+01, 7.86716400e+00, 9.54733115e+02, 1.77025533e+01, 8.08071917e+00, 1.15086354e+02, 1.89539967e+01, -1.15623253e-02, 3.42213001e+01, -3.47903570e+00],
     [2.41556742e+01, -1.98935098e+00, 2.46372149e+04, 4.97803249e+01, -1.08671456e+01, 2.22683176e+03, -6.57112562e-03, -1.88895586e+01, -3.47903570e+00, 4.95779720e+01]]
)
x2 = np.array(
 [[ 1.03028100e+01],
 [-1.24516793e+01],
 [ 1.81730518e+07],
 [ 8.00486315e+00],
 [ 2.72422816e+00],
 [ 1.68789702e+05],
 [-1.01153989e-01],
 [-4.62949462e-02],
 [-3.36991220e-02],
 [-1.05042425e-01]]
)

In [9]:
np.linalg.eigvals(P2)

array([1.30131606e+12, 9.72665683e+06, 3.71650187e+02, 3.73825994e+02,
       6.45319162e+01, 6.52977334e+01, 4.19813942e+01, 4.22670046e+01,
       1.03638711e+01, 1.04111045e+01])

In [10]:
points.sigma_points(x2.reshape(-1,), P2)

array([[ 1.03028100e+01, -1.24516793e+01,  1.81730518e+07,
         8.00486315e+00,  2.72422816e+00,  1.68789702e+05,
        -1.01153989e-01, -4.62949462e-02, -3.36991220e-02,
        -1.05042425e-01],
       [ 1.03070646e+01, -1.24516747e+01,  1.81730521e+07,
         8.00855601e+00,  2.72403371e+00,  1.68789732e+05,
        -1.01201068e-01, -4.61112110e-02, -3.34545987e-02,
        -1.04474674e-01],
       [ 1.03028100e+01, -1.24474157e+01,  1.81730518e+07,
         8.00506330e+00,  2.72792509e+00,  1.68789705e+05,
        -1.01722669e-01, -4.65383732e-02, -3.35148673e-02,
        -1.05089696e-01],
       [ 1.03028100e+01, -1.24516793e+01,  1.81734125e+07,
         8.00486669e+00,  2.72422802e+00,  1.68792560e+05,
        -1.01152401e-01, -4.63000343e-02, -3.36991157e-02,
        -1.05036134e-01],
       [ 1.03028100e+01, -1.24516793e+01,  1.81730518e+07,
         8.00783728e+00,  2.72423347e+00,  1.68789738e+05,
        -1.01424271e-01, -4.62372909e-02, -3.34199183e-02,
        -1.

In [11]:
q = [0.1, 0.1, 0.1]
i = np.eye(len(q))
Q = np.array([[val * num for num in i[ind]] for ind, val in enumerate(q)])

noise = np.random.multivariate_normal(np.zeros(Q.shape[0]), Q, 10)
noise

array([[ 0.23693837, -0.10835531,  0.15903746],
       [ 0.42232157,  0.0836173 , -0.00562657],
       [-0.27285721,  0.47696141, -0.25503993],
       [ 0.10487999,  0.79587138, -0.07330126],
       [-0.12216642,  0.11920633, -0.05050964],
       [ 0.05962228, -0.21390148,  0.28111115],
       [-0.05347519, -0.19462194,  0.08409137],
       [-0.08781583, -0.05157778, -0.03644325],
       [-0.4440617 , -0.40110537,  0.44385441],
       [ 0.60600897, -0.42081605,  0.06904846]])

In [12]:
np.ones((10, 3)) + noise

array([[1.23693837, 0.89164469, 1.15903746],
       [1.42232157, 1.0836173 , 0.99437343],
       [0.72714279, 1.47696141, 0.74496007],
       [1.10487999, 1.79587138, 0.92669874],
       [0.87783358, 1.11920633, 0.94949036],
       [1.05962228, 0.78609852, 1.28111115],
       [0.94652481, 0.80537806, 1.08409137],
       [0.91218417, 0.94842222, 0.96355675],
       [0.5559383 , 0.59889463, 1.44385441],
       [1.60600897, 0.57918395, 1.06904846]])

## Assumption

Since Unscented Kalman Filter has a recursive process meaning that if error between estimates and measured vector are corrected properly in measurement update step, the mean and its error covariance matrix continuously grow over time, causing the "4-th leading minor of the array is not positive definite" error since the covariance matrix P breaks a convention that the matrix has to be positive-definite meaning that all the eigenvalues need to be positive or zero.